app/golf_project/golf_app/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from .views import home, HoleListView, HoleUpdateView, user_registration, HoleCreateView, HoleDetailView, \
    ScorecardListView, ScorecardCreateView, CommentListView, CommentUpdateView, CommentDeleteView, CommentCreateView, \
    ScorecardDetailView, ScorecardDeleteView, HoleDeleteView, IndexView, graphs


from django.contrib.auth.views import login, logout

app_name ='golf_app'


urlpatterns = [
    url(r'^holes/$', HoleListView.as_view(),name="holes"),
    url(r'^update_hole/(?P<pk>\d+)/$', HoleUpdateView.as_view(),name="update_hole"),
    url(r'^home/$',home,name="home"),
    url(r'^registration/$', user_registration, name="user_registration"),
    url(r'^logout/$', logout, {'next_page': 'golf_app:home'}, name="logout"),
    url(r'^accounts/login/$',login, name="login"),
    url(r'^create_hole/(?P<pk>\d+)$', HoleCreateView.as_view(), name="create_hole"),
    url(r'^hole_detail/(?P<pk>\d+)/$', HoleDetailView.as_view(), name="hole_detail"),
    url(r'^scorecard_history/$', ScorecardListView.as_view(), name="scorecard_history"),
    url(r'^create_scorecard/$', ScorecardCreateView.as_view(), name="create_scorecard"),
    url(r'^comment_history/$', CommentListView.as_view(), name="comment_history"),
    url(r'^update_comment/(?P<pk>\d+)/$', CommentUpdateView.as_view(), name="update_comment"),
    url(r'^delete_comment/(?P<pk>\d+)$', CommentDeleteView.as_view(), name="delete_comment"),
    url(r'^create_comment/$', CommentCreateView.as_view(), name="create_comment"),
    url(r'^scorecard_detail/(?P<pk>\d+)$', ScorecardDetailView.as_view(), name="scorecard_detail"),
    url(r'^delete_scorecard/(?P<pk>\d+)$', ScorecardDeleteView.as_view(), name="delete_scorecard"),
    url(r'^delete_hole/(?P<pk>\d+)$', HoleDeleteView.as_view(), name="delete_hole"),
    url(r'^index/$', IndexView.as_view(), name="index"),
    url(r'^graph/$',graphs , name="graph"),

]

app/golf_project/golf_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^golf/', include('golf_app.urls')),
]

app/golf_project/golf_app/forms.py
from django import forms
from django.contrib.auth.models import User
from golf_app.models import Golfer


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')

class GolferForm(forms.ModelForm):
    class Meta:
        model = Golfer
        fields = ('name',)

app/golf_project/golf_app/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response, redirect
from django.template import RequestContext
from django.utils.decorators import method_decorator
from django.views.generic import ListView, UpdateView, CreateView, DetailView, DeleteView, TemplateView
from rest_framework import serializers
from rest_framework import generics
from golf_app.converter import scatter_to_base64, scatter_to_base641, scatter_to_base642
from .models import Hole, Scorecard, Comment, Golfer
from .forms import UserForm, GolferForm
import seaborn


class IndexView(TemplateView):
    template_name = "golf_app/index.html"


def user_registration(request):
    context = RequestContext(request)
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        golfer_form = GolferForm(data=request.POST)
        if user_form.is_valid() and golfer_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            golfer = golfer_form.save(commit=False)
            golfer.player = user
            golfer.save()
            registered = True
            return redirect("golf_app:login")
        else:
            pass
    else:
        user_form = UserForm()
        golfer_form = GolferForm()
    return render(request,'registration/create_user.html', {'user_form': user_form, 'golfer_form': golfer_form, 'registered': registered})


@login_required(login_url='golf_app:login')
def graphs(request):
    golfer = Golfer.objects.get(player=request.user)
    top_score = Scorecard.objects.get_best_scorecard(golfer)
    top_player_scores = Scorecard.objects.top_5_player_scores(golfer)
    top_player_gir = Scorecard.objects.top_5_gir(golfer)
    top_player_fir = Scorecard.objects.top_5_fir(golfer)

    graph_one = scatter_to_base64((range(len((golfer.scores_for_scorecards))), (golfer.scores_for_scorecards)), request.user)
    data = (request.user.golfer.par_type_list, (golfer.gir_for_scorecards))
    graph_two = scatter_to_base641(data, request.user)

    data_1 = (request.user.golfer.par_type_list, (golfer.fir_for_scorecards))
    graph_three = scatter_to_base642(data_1, request.user)
    return render(request,'golf_app/scorecard_graphs.html', {"graph_one": graph_one,
                                                                 "graph_two": graph_two,
                                                                 "graph_three": graph_three,
                                                                 "top_score": top_score,
                                                                 "top_player_scores" : top_player_scores,
                                                                 "top_player_gir": top_player_gir,
                                                                 "top_player_fir": top_player_fir})

def home(request):

    #golfer = Golfer.objects.get(player=request.user)
    #top_score = Scorecard.objects.get_best_scorecard(golfer)
    context = {}
    return render(request,"home.html" ,context)

# Not sure if I even need serializers yet!!
class HoleDetailSerializer(serializers.ModelSerializer):
    class Meta:
        model = Hole
        fields = ['scorecard', 'hole_number', 'par_type', 'hole_length',
                  'player_score', 'green_in_regulation', 'fairway_in_regulation', 'timestamp']


class HoleListSerializer(serializers.ModelSerializer):
    class Meta:
        model = Hole
        fields = ['hole_number', 'par_type', 'hole_length', 'player_score', 'green_in_regulation',
                  'fairway_in_regulation']


class HoleListView(ListView):
    model = Hole
    # fields = ['hole_number','par_type','hole_length', 'player_score','green_in_regulation', 'fairway_in_regulation']
    template = "scorecard_detail.html"
    success_url = reverse_lazy("golf_app:scorecard_detail")

class HoleUpdateView(UpdateView):
    model = Hole
    fields = ['par_type','player_score','green_in_regulation', 'fairway_in_regulation','putts']
    template = "hole_form.html"
    success_url = reverse_lazy("golf_app:scorecard_detail")


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['scorecard_pk'] = self.kwargs.get('pk')
        return context

    def form_valid(self, form):
        score_pk = Hole.objects.get(id=self.kwargs['pk']).scorecard.id
        form.instance.scorecard_id = score_pk
        form.instance.scorecard = Hole.objects.get(id=self.kwargs['pk']).scorecard
        self.success_url = reverse_lazy("golf_app:scorecard_detail", kwargs={'pk': score_pk})
        return super().form_valid(form)

    @method_decorator(login_required(login_url='golf_app:login'))
    def dispatch(self, *args, **kwargs):
        return super(HoleUpdateView, self).dispatch(*args, **kwargs)


class HoleCreateView(CreateView):
    model = Hole
    fields = ['hole_number','par_type','player_score', 'green_in_regulation', 'fairway_in_regulation','putts']
    template_name = "golf_app/create_hole.html"
    #success_url = reverse_lazy("golf_app:scorecard_detail")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['scorecard_pk'] = self.kwargs.get('pk')
        return context

    #Thank you Bekk!!!!!! He helped me a lot with this!!
    def form_valid(self, form):
        score_pk = self.kwargs['pk']
        form.instance.scorecard_id = self.kwargs['pk']
        form.instance.scorecard = Scorecard.objects.get(id=self.kwargs['pk'])
        self.success_url = reverse_lazy("golf_app:scorecard_detail", kwargs={'pk': score_pk})
        return super().form_valid(form)

    @method_decorator(login_required(login_url='golf_app:login'))
    def dispatch(self, *args, **kwargs):
        return super(HoleCreateView, self).dispatch(*args, **kwargs)


class HoleDetailView(DetailView):
    model = Hole
    fields = ['scorecard', 'hole_number', 'hole_length', 'player_score', 'green_in_regulation','fairway_in_regulation','putts']
    success_url = reverse_lazy("golf_app:scorecard_detail")
    template = "golf_app/hole_detail.html"
    slug_field = "id"

    @method_decorator(login_required(login_url="golf_app:login"))
    def dispatch(self, *args, **kwargs):
        return super(HoleDetailView, self).dispatch(*args, **kwargs)


class HoleDeleteView(DeleteView):
    model = Hole

    def get_success_url(self):
        return reverse('golf_app:scorecard_detail', kwargs={'pk':self.object.scorecard.pk})


class ScorecardListView(ListView):
    model = Scorecard
    fields = ['player', 'course_name','par_total', 'course_length', 'timestamp']
    template = "scorecard_list.html"
    success_url = reverse_lazy("golf_app:scorecard_history")

    def get_queryset(self):
        return Scorecard.objects.filter(player__player=self.request.user)

    @method_decorator(login_required(login_url='golf_app:login'))
    def dispatch(self, *args, **kwargs):
        return super(ScorecardListView, self).dispatch(*args, **kwargs)

class ScorecardDetailView(DetailView):
    model = Scorecard
    template = "scorecard_detail.html"

    @method_decorator(login_required(login_url='golf_app:login'))
    def dispatch(self, *args, **kwargs):
        return super(ScorecardDetailView, self).dispatch(*args,**kwargs)


class ScorecardCreateView(CreateView):
    model = Scorecard
    fields = ['course_name','par_total']
    template = "scorecard_form.html"
    #success_url = reverse_lazy("golf_app:scorecard_history")

    def form_valid(self, form):
        golfer = Golfer.objects.get(player=self.request.user)
        form.instance.player = golfer
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('golf_app:scorecard_detail', kwargs={'pk':self.object.id})

    @method_decorator(login_required(login_url='golf_app:login'))
    def dispatch(self, *args, **kwargs):
        return super(ScorecardCreateView, self).dispatch(*args, **kwargs)



class ScorecardDeleteView(DeleteView):
    model = Scorecard
    success_url = reverse_lazy("golf_app:scorecard_history")

    @method_decorator(login_required(login_url='golf_app:login'))
    def dispatch(self, *args, **kwargs):
        return super(ScorecardDeleteView, self).dispatch(*args, **kwargs)


class CommentListView(ListView):
    model = Comment
    fields = ['player', 'course_name', 'comment', 'course_rating', 'timestamp']
    template = "course_list.html"
    success_url = reverse_lazy('golf_app:comment_history')


class CommentUpdateView(UpdateView):
    model = Comment
    fields = ['course_name', 'comment', 'course_rating']
    template = "comment_form.html"
    success_url = reverse_lazy('golf_app:comment_history')

    @method_decorator(login_required(login_url='golf_app:login'))
    def dispatch(self, *args, **kwargs):
        return super(CommentUpdateView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Comment.objects.filter(player__player=self.request.user)

class CommentDeleteView(DeleteView):
    model = Comment
    success_url = reverse_lazy('golf_app:comment_history')

    @method_decorator(login_required(login_url='golf_app:login'))
    def dispatch(self, *args, **kwargs):
        return super(CommentDeleteView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Comment.objects.filter(player__player=self.request.user)

class CommentCreateView(CreateView):
    model = Comment
    fields = ['course_name', 'comment', 'course_rating']
    template = "comment_form.html"
    success_url = reverse_lazy('golf_app:comment_history')

    def form_valid(self, form):
        golfer = Golfer.objects.get(player=self.request.user)

app/golf_project/golf_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title></title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'css/materialize.css'%}" type="text/css" rel="stylesheet" media="screen,projection" />
    <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection" />

</head>
{% block head %}
{% endblock %}

<body>
  <nav class="top-nav" role="navigation">
      <ul class="right hide-on-med-and-down">
      <strong><li><a href="{% url 'golf_app:home' %}">Home</a></li></strong>
      <strong><li><a href="{% url 'golf_app:scorecard_history' %}">Scorecards</a></li></strong>
      <strong><li><a href="{% url 'golf_app:comment_history' %}">Course Comments</a></li></strong>
      <strong><li><a href="{% url 'golf_app:graph' %}">Scorecard Analysis</a></li></strong>
          {% if user.id %}
          <strong><li><a href="{% url 'golf_app:logout' %}">Logout</a></li></strong>
            {% else %}
            <strong><li><a href="{% url 'golf_app:login' %}">Login</a></li></strong>
             <strong><li><a href="{% url 'golf_app:user_registration' %}">Sign up</a></li></strong>
            {% endif %}
      </ul>
      <div id="side-nav-bar">
      <ul id="nav-mobile" class="side-nav">
      <li><a href="{% url 'golf_app:home' %}" style="color:white;">Home</a></li>
      <li><a href="{% url 'golf_app:scorecard_history' %}" style="color:white;">Scorecards</a></li>
      <li><a href="{% url 'golf_app:graph' %}" style="color:white;">Scorecard Analysis</a></li>
      <li><a href="{% url 'golf_app:comment_history' %}" style="color:white;">Course Comments</a></li>
      {% if user.id %}
          <strong><li><a href="{% url 'golf_app:logout' %}" style="color:white;">Logout</a></li></strong>
            {% else %}
            <strong><li><a href="{% url 'golf_app:login' %}" style="color:white;">Login</a></li></strong>
             <strong><li><a href="{% url 'golf_app:user_registration' %}" style="color:white;">Sign up</a></li></strong>
            {% endif %}
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
  </div>
  </nav>
{% block body %}
{% endblock %}
{% block content %}
{% endblock %}
  <p></p>
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'js/materialize.js' %}"></script>
  <script src="{% static 'js/init.js' %}"></script>
</body>
</html>

app/golf_project/golf_app/templates/home.html
{% load static  %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title></title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'css/materialize.css'%}" type="text/css" rel="stylesheet" media="screen,projection" />
    <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection" />

</head>
{% block head %}
{% endblock %}
<body>
  <nav class="top-nav" role="navigation">
      <ul class="right hide-on-med-and-down">
      <strong><li><a href="{% url 'golf_app:home' %}">Home</a></li></strong>
      <strong><li><a href="{% url 'golf_app:scorecard_history' %}">Scorecards</a></li></strong>
      <strong><li><a href="{% url 'golf_app:comment_history' %}">Course Comments</a></li></strong>
      <strong><li><a href="{% url 'golf_app:graph' %}">Scorecard Analysis</a></li></strong>
          {% if user.id %}
          <strong><li><a href="{% url 'golf_app:logout' %}">Logout</a></li></strong>
            {% else %}
            <strong><li><a href="{% url 'golf_app:login' %}">Login</a></li></strong>
             <strong><li><a href="{% url 'golf_app:user_registration' %}">Sign up</a></li></strong>
            {% endif %}
      </ul>
      <div class="side-nav-bar">
          <ul id="nav-mobile" class="side-nav">
            <li><a href="{% url 'golf_app:home' %}" style="color:white;">Home</a></li>
          <li><a href="{% url 'golf_app:scorecard_history' %}" style="color:white;">Scorecards</a></li>
          <li><a href="{% url 'golf_app:graph' %}" style="color:white;">Scorecard Analysis</a></li>
          <li><a href="{% url 'golf_app:comment_history' %}" style="color:white;">Course Comment</a></li>
            {% if user.id %}
               <li><a href="{% url 'golf_app:logout' %}" style="color:white;">Logout</a></li>
            {% else %}
                <li><a href="{% url 'golf_app:login' %}" style="color:white;">Login</a></li>
                <li><a href="{% url 'golf_app:user_registration' %}" style="color:white;">Sign up</a></li>
            {% endif %}
          </ul>
          <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
      </div>
  </nav>
    {% block body %}
        <h1 align="center">Fore Score</h1>
    <h5 align="center" class="welcome-font">Welcome {{ user.username }}!</h5>
    {% endblock %}
  <div align="center">
    <button class="light green waves-dark btn-large gray begin-round">
        <a class="white-text" href="{% url 'golf_app:scorecard_history' %}">
            <strong>Add Scorecard to Begin</strong>
        </a>
    </button>
  </div>
    {% block content %}
    {% endblock %}
  <div class="container" style="background-color:#C8E6C9; width:55%; margin-top:20px;">
    <table align="center" class="bordered" style="background-color: white;">
        <tr>
            <td><h5>Average Score:</h5></td>
            <td><h5>{{ user.golfer.average_score }}</h5></td>
        </tr>
        <tr>
            <td><h5>Average GIR%:</h5></td>
            <td><h5>{{ user.golfer.average_gir }}</h5></td>
        </tr>
        <tr>
            <td><h5>Average FIR %:</h5></td>
            <td><h5>{{ user.golfer.average_fir }}</h5></td>
        </tr>
    </table>
  </div>

  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'js/materialize.js' %}"></script>
  <script src="{% static 'js/init.js' %}"></script>
</body>
</html>