app/golf_project/golf_app/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from .views import home, HoleListView, HoleUpdateView, user_registration, HoleCreateView, HoleDetailView, \
    ScorecardListView, ScorecardCreateView, CommentListView, CommentUpdateView, CommentDeleteView, CommentCreateView, \
    ScorecardDetailView, ScorecardDeleteView, HoleDeleteView, IndexView, graphs


from django.contrib.auth.views import login, logout

app_name ='golf_app'


urlpatterns = [
    url(r'^holes/$', HoleListView.as_view(),name="holes"),
    url(r'^update_hole/(?P<pk>\d+)/$', HoleUpdateView.as_view(),name="update_hole"),
    url(r'^home/$',home,name="home"),
    url(r'^registration/$', user_registration, name="user_registration"),
    url(r'^logout/$', logout, {'next_page': 'golf_app:home'}, name="logout"),
    url(r'^accounts/login/$',login, name="login"),
    url(r'^create_hole/(?P<pk>\d+)$', HoleCreateView.as_view(), name="create_hole"),
    url(r'^hole_detail/(?P<pk>\d+)/$', HoleDetailView.as_view(), name="hole_detail"),
    url(r'^scorecard_history/$', ScorecardListView.as_view(), name="scorecard_history"),
    url(r'^create_scorecard/$', ScorecardCreateView.as_view(), name="create_scorecard"),
    url(r'^comment_history/$', CommentListView.as_view(), name="comment_history"),
    url(r'^update_comment/(?P<pk>\d+)/$', CommentUpdateView.as_view(), name="update_comment"),
    url(r'^delete_comment/(?P<pk>\d+)$', CommentDeleteView.as_view(), name="delete_comment"),
    url(r'^create_comment/$', CommentCreateView.as_view(), name="create_comment"),
    url(r'^scorecard_detail/(?P<pk>\d+)$', ScorecardDetailView.as_view(), name="scorecard_detail"),
    url(r'^delete_scorecard/(?P<pk>\d+)$', ScorecardDeleteView.as_view(), name="delete_scorecard"),
    url(r'^delete_hole/(?P<pk>\d+)$', HoleDeleteView.as_view(), name="delete_hole"),
    url(r'^index/$', IndexView.as_view(), name="index"),
    url(r'^graph/$',graphs , name="graph"),

]

app/golf_project/golf_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^golf/', include('golf_app.urls')),
]

app/golf_project/golf_app/forms.py
from django import forms
from django.contrib.auth.models import User
from golf_app.models import Golfer


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')

class GolferForm(forms.ModelForm):
    class Meta:
        model = Golfer
        fields = ('name',)

app/golf_project/golf_app/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response, redirect
from django.template import RequestContext
from django.utils.decorators import method_decorator
from django.views.generic import ListView, UpdateView, CreateView, DetailView, DeleteView, TemplateView
from rest_framework import serializers
from rest_framework import generics
from golf_app.converter import scatter_to_base64, scatter_to_base641, scatter_to_base642
from .models import Hole, Scorecard, Comment, Golfer
from .forms import UserForm, GolferForm
import seaborn


class IndexView(TemplateView):
    template_name = "golf_app/index.html"


def user_registration(request):
    context = RequestContext(request)
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        golfer_form = GolferForm(data=request.POST)
        if user_form.is_valid() and golfer_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            golfer = golfer_form.save(commit=False)
            golfer.player = user
            golfer.save()
            registered = True
            return redirect("golf_app:login")
        else:
            pass
    else:
        user_form = UserForm()
        golfer_form = GolferForm()
    return render(request,'registration/create_user.html', {'user_form': user_form, 'golfer_form': golfer_form, 'registered': registered})


@login_required(login_url='golf_app:login')
def graphs(request):
    golfer = Golfer.objects.get(player=request.user)
    top_score = Scorecard.objects.get_best_scorecard(golfer)
    top_player_scores = Scorecard.objects.top_5_player_scores(golfer)
    top_player_gir = Scorecard.objects.top_5_gir(golfer)
    top_player_fir = Scorecard.objects.top_5_fir(golfer)

    graph_one = scatter_to_base64((range(len((golfer.scores_for_scorecards))), (golfer.scores_for_scorecards)), request.user)
    data = (request.user.golfer.par_type_list, (golfer.gir_for_scorecards))
    graph_two = scatter_to_base641(data, request.user)

    data_1 = (request.user.golfer.par_type_list, (golfer.fir_for_scorecards))
    graph_three = scatter_to_base642(data_1, request.user)
    return render(request,'golf_app/scorecard_graphs.html', {"graph_one": graph_one,
                                                                 "graph_two": graph_two,
                                                                 "graph_three": graph_three,
                                                                 "top_score": top_score,
                                                                 "top_player_scores" : top_player_scores,
                                                                 "top_player_gir": top_player_gir,
                                                                 "top_player_fir": top_player_fir})

def home(request):

    #golfer = Golfer.objects.get(player=request.user)
    #top_score = Scorecard.objects.get_best_scorecard(golfer)
    context = {}
    return render(request,"home.html" ,context)

# Not sure if I even need serializers yet!!
class HoleDetailSerializer(serializers.ModelSerializer):
    class Meta:
        model = Hole
        fields = ['scorecard', 'hole_number', 'par_type', 'hole_length',
                  'player_score', 'green_in_regulation', 'fairway_in_regulation', 'timestamp']


class HoleListSerializer(serializers.ModelSerializer):
    class Meta:
        model = Hole
        fields = ['hole_number', 'par_type', 'hole_length', 'player_score', 'green_in_regulation',
                  'fairway_in_regulation']


class HoleListView(ListView):
    model = Hole
    # fields = ['hole_number','par_type','hole_length', 'player_score','green_in_regulation', 'fairway_in_regulation']
    template = "scorecard_detail.html"
    success_url = reverse_lazy("golf_app:scorecard_detail")

class HoleUpdateView(UpdateView):
    model = Hole
    fields = ['par_type','player_score','green_in_regulation', 'fairway_in_regulation','putts']
    template = "hole_form.html"
    success_url = reverse_lazy("golf_app:scorecard_detail")


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['scorecard_pk'] = self.kwargs.get('pk')
        return context

    def form_valid(self, form):
        score_pk = Hole.objects.get(id=self.kwargs['pk']).scorecard.id
        form.instance.scorecard_id = score_pk
        form.instance.scorecard = Hole.objects.get(id=self.kwargs['pk']).scorecard
        self.success_url = reverse_lazy("golf_app:scorecard_detail", kwargs={'pk': score_pk})
        return super().form_valid(form)

    @method_decorator(login_required(login_url='golf_app:login'))
    def dispatch(self, *args, **kwargs):
        return super(HoleUpdateView, self).dispatch(*args, **kwargs)


class HoleCreateView(CreateView):
    model = Hole
    fields = ['hole_number','par_type','player_score', 'green_in_regulation', 'fairway_in_regulation','putts']
    template_name = "golf_app/create_hole.html"
    #success_url = reverse_lazy("golf_app:scorecard_detail")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['scorecard_pk'] = self.kwargs.get('pk')
        return context

    #Thank you Bekk!!!!!! He helped me a lot with this!!
    def form_valid(self, form):
        score_pk = self.kwargs['pk']
        form.instance.scorecard_id = self.kwargs['pk']
        form.instance.scorecard = Scorecard.objects.get(id=self.kwargs['pk'])
        self.success_url = reverse_lazy("golf_app:scorecard_detail", kwargs={'pk': score_pk})
        return super().form_valid(form)

    @method_decorator(login_required(login_url='golf_app:login'))
    def dispatch(self, *args, **kwargs):
        return super(HoleCreateView, self).dispatch(*args, **kwargs)


class HoleDetailView(DetailView):
    model = Hole
    fields = ['scorecard', 'hole_number', 'hole_length', 'player_score', 'green_in_regulation','fairway_in_regulation','putts']
    success_url = reverse_lazy("golf_app:scorecard_detail")
    template = "golf_app/hole_detail.html"
    slug_field = "id"

    @method_decorator(login_required(login_url="golf_app:login"))
    def dispatch(self, *args, **kwargs):
        return super(HoleDetailView, self).dispatch(*args, **kwargs)


class HoleDeleteView(DeleteView):
    model = Hole

    def get_success_url(self):
        return reverse('golf_app:scorecard_detail', kwargs={'pk':self.object.scorecard.pk})


class ScorecardListView(ListView):
    model = Scorecard
    fields = ['player', 'course_name','par_total', 'course_length', 'timestamp']
    template = "scorecard_list.html"
    success_url = reverse_lazy("golf_app:scorecard_history")

    def get_queryset(self):
        return Scorecard.objects.filter(player__player=self.request.user)

    @method_decorator(login_required(login_url='golf_app:login'))
    def dispatch(self, *args, **kwargs):
        return super(ScorecardListView, self).dispatch(*args, **kwargs)

class ScorecardDetailView(DetailView):
    model = Scorecard
    template = "scorecard_detail.html"

    @method_decorator(login_required(login_url='golf_app:login'))
    def dispatch(self, *args, **kwargs):
        return super(ScorecardDetailView, self).dispatch(*args,**kwargs)


class ScorecardCreateView(CreateView):
    model = Scorecard
    fields = ['course_name','par_total']
    template = "scorecard_form.html"
    #success_url = reverse_lazy("golf_app:scorecard_history")

    def form_valid(self, form):
        golfer = Golfer.objects.get(player=self.request.user)
        form.instance.player = golfer
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('golf_app:scorecard_detail', kwargs={'pk':self.object.id})

    @method_decorator(login_required(login_url='golf_app:login'))
    def dispatch(self, *args, **kwargs):
        return super(ScorecardCreateView, self).dispatch(*args, **kwargs)



class ScorecardDeleteView(DeleteView):
    model = Scorecard
    success_url = reverse_lazy("golf_app:scorecard_history")

    @method_decorator(login_required(login_url='golf_app:login'))
    def dispatch(self, *args, **kwargs):
        return super(ScorecardDeleteView, self).dispatch(*args, **kwargs)


class CommentListView(ListView):
    model = Comment
    fields = ['player', 'course_name', 'comment', 'course_rating', 'timestamp']
    template = "course_list.html"
    success_url = reverse_lazy('golf_app:comment_history')


class CommentUpdateView(UpdateView):
    model = Comment
    fields = ['course_name', 'comment', 'course_rating']
    template = "comment_form.html"
    success_url = reverse_lazy('golf_app:comment_history')

    @method_decorator(login_required(login_url='golf_app:login'))
    def dispatch(self, *args, **kwargs):
        return super(CommentUpdateView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Comment.objects.filter(player__player=self.request.user)

class CommentDeleteView(DeleteView):
    model = Comment
    success_url = reverse_lazy('golf_app:comment_history')

    @method_decorator(login_required(login_url='golf_app:login'))
    def dispatch(self, *args, **kwargs):
        return super(CommentDeleteView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Comment.objects.filter(player__player=self.request.user)

class CommentCreateView(CreateView):
    model = Comment
    fields = ['course_name', 'comment', 'course_rating']
    template = "comment_form.html"
    success_url = reverse_lazy('golf_app:comment_history')

    def form_valid(self, form):
        golfer = Golfer.objects.get(player=self.request.user)

app/golf_project/golf_app/templates/golf_app/comment_confirm_delete.html
{% extends 'base.html' %}
{% block body %}
<body>
</br>
    <h5 align="center" class="delete-comment-q" style="padding:5%;" >Are you sure you want to delete this comment and rating for {{ comment.course_name }}?</h5>
        <div align="center">
            <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="red btn"><strong>Delete Comment</strong></button>
            </form>
        </div>

{% endblock %}

</body>

</html>

app/golf_project/golf_app/templates/golf_app/comment_form.html
{% extends 'base.html' %}


    <body>
        {% block body %}
            <div class="edit-comment-form">
                <div style="padding-top: 1px; padding-right:20%; padding-left: 20%;">
                    <form method="POST" class="edit-comment">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="green btn">Submit</button>
                    </form>
                </div>
            </div>
        {% endblock %}
    </body>

app/golf_project/golf_app/templates/golf_app/comment_list.html
{% extends 'base.html' %}

<body>
{% block body %}
<h1 class="Comment-title" align="center">Comments</h1>
        <div align="center">
            <form method="get" action="{% url 'golf_app:create_comment' %}">
                {% csrf_token %}
                <button type="submit" class="green waves-dark btn-large"><strong>Add Comment</strong></button>
            </form>
        </div>
    {% for comment in object_list %}
        <div align="left">
            <div class="col s12 m6">
                <div class="container" style="padding-top: 5px; padding-bottom: 1px;">
                  <div class="card light-green lighten-4">
                    <div class="card-content black-text">
                        {% if comment.player == request.user.golfer %}
                            <div align="right" style="float:right;">
                                <form id="linked" method="get" action="{% url 'golf_app:delete_comment' comment.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="delete-comment"><strong><i class="material-icons">delete</i></strong></button>
                                </form>
                            </div>
                            <div align="left" style="float:left;">
                                <form id="linked" method="get" action="{% url 'golf_app:update_comment' comment.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="edit-comment"><i class="mdi-content-create" style="font-size: 22px;"></i></button>
                                </form>
                            </div>

                        {% else %}

                        {% endif %}
                        <div>
                            <br/>
                            <br/>
                            <span class="card-title black-text" style="margin-top:5px;"><strong>{{ comment.course_name }}</strong></span>
                            <ul>
                                <p>
                               <li><strong>Comment:</strong> {{ comment.comment }}</li>
                               <li><strong>Rating:</strong> {{ comment.course_rating }}</li>
                               <li><strong>Posted:</strong> {{ comment.timestamp }}</li>
                                </p>
                            </ul>
                        </div>
                      </div>
                   </div>
              </div>
            </div>
        </div>
            </br>
        {% endfor %}
{% endblock %}

</body>

app/golf_project/golf_app/templates/golf_app/create_hole.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
 </head>
<body>
{% block body %}

<a href="{% url 'golf_app:scorecard_detail' scorecard_pk %}">Back</a>
    <h1>Create Hole</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="post">Add Hole!</button>
    </form>

{% endblock %}
</body>

</html>

app/golf_project/golf_app/templates/golf_app/hole_confirm_delete.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>

</head>

{% block body %}
<a href="{%  url 'golf_app:home' %}">Home</a>
<a href="{% url 'golf_app:scorecard_history' %}">Scorecard History</a>
<body>
</br>
<p>Are you sure you want to delete this hole?</p>
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit"><strong>Delete Hole</strong></button>

</form>

{% endblock %}

</body>

</html>

app/golf_project/golf_app/templates/golf_app/hole_detail.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
 </head>
<body>

{% block body %}
    <p align="center">
            <a href="{%  url 'golf_app:scorecard_detail' hole.scorecard.id %}" class="green waves-light btn"> {{ hole.scorecard.course_name }} Scorecard</a>
    </p>
    <div class="container" style="background-color: #607D8B; margin-top:20px;">
        <div style="padding-top: 10px; padding-bottom: 10px; background-color:#C8E6C9;">
            <div class="hole-detail">
                <form method="get" action="{% url 'golf_app:update_hole' hole.id %}">
                        <button type="submit" class="edit-hole">
                            <h4><i class="mdi-content-create" style="width:50px;"></i></h4>
                        </button>
                        {% csrf_token %}
                    </form>
                <h2>Hole {{ hole.hole_number }} Detail</h2>
                <a href="{% url 'golf_app:scorecard_history' %}">{{ scorecard.course_name }}</a>
                <div class="hole-detail-info">
                    <ul>
                        <li><strong>Hole Number:</strong> {{ hole.hole_number }}</li>
                        <li><strong>Par Type</strong>: {{ hole.par_type }}</li>
                        <li><strong>Player Score:</strong> {{ hole.player_score }}</li>
                        <li><strong>GIR:</strong> {{ hole.gir }}</li>
                        <li><strong>FIR:</strong> {{ hole.fir }}</li>
                        <li><strong># of Putts:</strong> {{ hole.putts }}</li>
                        <li><strong>When:</strong> {{ hole.timestamp }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
            <div class="container" style="background-color:ghostwhite;">
                <div class="previous-btn">
                    {% if hole.previous_hole %}
                        <a href="{% url 'golf_app:hole_detail' hole.previous_hole.id %}"><i class="large material-icons" style="color:green;vertical-align:middle;">trending_flat</i></a>
                    {% else %}
                        <i class="large material-icons" style="color:red;">trending_flat</i>
                    {% endif %}
                </div>
                <div class="next-btn">
                    {% if hole.next_hole %}
                        <a href="{% url 'golf_app:hole_detail' hole.next_hole.id %}"><i class="large material-icons" style="color:green;vertical-align:middle;">trending_flat</i></a>
                    {% else %}
                        <i class="large material-icons" style="color:red;">trending_flat</i>
                    {% endif %}
                </div>
            </div>



{% endblock %}
</body>

</html>

app/golf_project/golf_app/templates/golf_app/hole_form.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>

</head>
<body>
{% block body %}
    <div class="scorecard-button-hole" align="center">
        <a href="{% url 'golf_app:scorecard_detail' hole.scorecard.id  %}" class="green waves-light btn">{{ hole.scorecard.course_name }} Scorecard</a>
    </div>
    <br/>
<br/>
    <div class="hole-detail">
        <h2 align="center">Hole Number: {{ hole.hole_number }}</h2>
    </div>
        <div class="container" style="background-color:ghostwhite;">
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                    <p>
                    {% if field.id_for_label == "id_green_in_regulation" or field.id_for_label == "id_fairway_in_regulation" %}
                   <div class="checkbox-fix">
                       <label style="color:black;">{{ field.label }}</label>{{ field }}:
                       <label for="{{ field.id_for_label }}"></label>
                   </div>
                    {% else %}
                        <label style="color:black;">{{ field.label }}:</label>{{ field }}
                    {%  endif %}
                    </p>
                {% endfor %}
                <button type="submit" value="update" class="green btn">Submit</button>
            </form>
        </div>
    <div class="back-btn-hole" align="center">
        <a href="{% url 'golf_app:hole_detail' hole.id %}" class="btn" style="background-color:#607D8B;"><strong>Back</strong></a>
    </div>
{% endblock %}

</body>
</html>

app/golf_project/golf_app/templates/golf_app/scorecard_confirm_delete.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>

</head>

{% block body %}
<body>
</br>
            <h4 align="center" class="confirm-del">Are you sure you want to delete the {{ scorecard.course_name }} scorecard?</h4>
                <form method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <div align="center">
                    <button type="submit" class="red btn"><strong>Delete Scorecard</strong></button>
                    </div>
                </form>
{% endblock %}
</body>
</html>

app/golf_project/golf_app/templates/golf_app/scorecard_detail.html
{% extends 'base.html' %}

{% block body %}

    <div class="player-info">
     <div align="center"><h3>{{ scorecard.course_name }}</h3></div>
     <div align="center"><strong>Total Score:</strong> {{ scorecard.hole_score }}</div>
     <div align="center"><strong>GIR %:</strong> {{ scorecard.gir_percentage }}</div>
     <div align="center"><strong>FIR %:</strong> {{ scorecard.fir_percentage }}</div>
     <div align="center"><strong>Score to Par:</strong> {{ scorecard.over_under_par }}</div>
     <div align="center"><strong>Front 9({{scorecard.front_nine_to_par}}):</strong> {{ scorecard.front_nine_total}}</div>
     <div align="center"><strong>Back 9({{scorecard.back_nine_to_par }}):</strong> {{ scorecard.back_nine_total}}</div>
     <div align="center"><strong># of Putts:</strong> {{scorecard.putt_total }}</div>


    </div>
    <table>
      <tr>
        <th></th>

      </tr>
    </table>

</br>
    <div class="container" id="sc-detail-tb" style="background-color:#607D8B;">
      <table class="hoverable" style="background-color:#C8E6C9;">
        <thead>
          <tr>
              <th data-field="id" style="text-align:center;"><h5>Player Score</h5></th>
              <th data-field="id" style="text-align:center;"><h5>Hole Number</h5></th>
              <th data-field="id" style="text-align:center;"><h5>Over/Under Par(-)</h5></th>
          </tr>
        </thead>
        <tbody>
        {% for hole in object.hole_set.all %}

          <tr>
            <td style="text-align:center;"><a href="{% url 'golf_app:hole_detail' hole.id %}"><h5><strong><div style="color:black;">{{ hole.player_score }}</div></strong></h5></a></td>
            <td style="text-align:center;"><strong><h5><a href="{% url 'golf_app:hole_detail' hole.id %}" class="green btn">{{ hole.hole_number }}</a></h5></strong></td>
            <td style="text-align:center;"><a href="{% url 'golf_app:hole_detail' hole.id %}"><h5><strong><div style="color:black;">{{ hole.hole_over_under_par }}</div></strong></h5></a></td>
          </tr>

        {% endfor %}
        </tbody>
      </table>
    </div>


{% endblock %}

app/golf_project/golf_app/templates/golf_app/scorecard_form.html
{% extends 'base.html' %}

{% block body %}
  <div class="add-scorecard">
        <form method="POST" class="scorecard-name">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="green btn">Add Scorecard</button>
        </form>
    </div>

{% endblock %}

app/golf_project/golf_app/templates/golf_app/scorecard_graphs.html
{% extends 'base.html' %}

{% block content %}
    <div align="center" class="best_score">
        <ul>
            <li><h5>Best Score:</h5></li>
            <li><h5>{{ top_score }} ({{ top_score.hole_score }})</h5></li>

        </ul>
    </div>
     <div class="bar-graph" align="center">
        <div class="container" style="background-color:ghostwhite; width:100%; height:auto;">
           <img src="{{ graph_one }}" class="materialboxed" width="90%" style="border:15px solid grey;">
        </div>
        <ol>
                {% comment %}{% for score in top_player_scores %}
                    {{ top_player_scores }} {{ top_player_scores.hole_score }}
                {% endfor %}{% endcomment %}
         </ol>
     </div>
        <div class="gir-line" align="center">
            <div class="container" style="width:100%; height:auto; background-color:ghostwhite;">
                <img src="{{ graph_two }}" class="materialboxed" width="90%" style="border:15px solid grey;"/>
            </div>
        {% comment %}{{ top_player_gir }} {% endcomment %}
        </div>
            <div class="fir-line" align="center">
                <div class="container" style="background-color:ghostwhite; width:100%; height:auto;">
                    <img src="{{ graph_three }}" class="materialboxed" width="90%" style="border:15px solid grey;"/>
                </div>
            </div>
        {% comment %}{{ top_player_fir }}{% endcomment %}
{% endblock %}

app/golf_project/golf_app/templates/golf_app/scorecard_list.html
{%  extends 'base.html' %}
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>

</head>
<body>
{% block body %}
<div class="scorecard-list">
    <h1 align="center">Scorecards</h1>

<div align="center" class="add-score-btn">
    <a href="{% url 'golf_app:create_scorecard' %}" class="green waves-dark btn-large">Begin Round</a>
</div>
  <div align="center" class="container" style="background-color:#607D8B">
    <table align="center" class="hoverable">
            <th><font color="black"><h5><strong>Recent Scorecards</strong></h5></font></th>
            <th><h5><strong>Created On</strong></h5></th>
            <th></th>
                {% for scorecard in object_list %}
                <tr>
                    <td>
                        <a href="{% url 'golf_app:scorecard_detail' scorecard.id %}" style="color: darkgreen;">
                        <u><h5><strong>{{ scorecard.course_name }}</strong></h5></u></a>
                    </td>
                     <td>
                         <div class="timestamp-sc"> {{ scorecard.timestamp }}</div>
                    </td>
                    <td>
                        <form method="get" action="{% url 'golf_app:delete_scorecard' scorecard.id %}">
                            {% csrf_token %}
                            <button type="submit" class="delete-sc-list"><i class="material-icons">delete</i></button>
                        </form>
                    </td>
                </tr>
        {% endfor %}
    </table>
  </div>
{% endblock %}
</body>
</html>